{% set python_min = python_min|default("0.1a0") %}
{% set name = "types-pyRFC3339" %}
{% set version = "2.0.1.20241107" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pyRFC3339-{{ version }}.tar.gz
  sha256: 0f84380fc93c1c65fd45f06afc5ae0ef90874411780863525490c7924d85bc5d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}.*
  run:
    - python >={{ python_min }}

test:
  requires:
    - python ={{ python_min }}
  commands:
    - test -f $SP_DIR/pyrfc3339-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pyRFC3339
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
